spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/db_libreralozano?useSSL=false #Maquina Hugo
    url: jdbc:mysql://localhost:3308/db_librerialozano?useSSL=false #Maquina Luis
#    url: jdbc:mysql://localhost:3306/db_librerialozano?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      